### ISSUE TITLE
Peer Code Review From Anita

### ISSUE THREAD

**Issue by anita-epp** [Elizabeth1813/GDMA-2567-Client-Site#2]
This review is for HTML

- [ ] Line #14 - You probably don't need the "about" id or the "about" link in the nav since this is the top of the page and the link won't scroll anywhere else

- [ ] #15 utilize the class "bg-black" intstead of the id on the box

- [ ] #22 - be more specific "endless summer logo"

- [ ] #40 - should be a div since it has no header

- [ ] #43 - no section since is has no header; put the col class on the form

- [ ] #67 - place the paragraph outside of the UL 

- [ ] #96 - the button doesn't need a col class or push-right.  It should be in a div, not a section.

- [ ] For your packages section, keep all information for each package in the same larger section.  for instance, for your 5-day package, make sure all the info is in one large section because it all shares the same header.  Break up the first part of the info into a div floated left, and the list and button into a div floated right.

- [ ] #192 could be an aside instead of a div

- [ ] #196 - if bg is white you can put the wrapper class on the section and get rid of the div

- [ ] #201 - your 3 sections should be divs

- [ ] #214 - put wrapper class and ID on the section, get rid of the divs here unless you need them for background images

- [ ] #200 list the form div before the map div
